/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutPagoRouteImport } from './routes/checkout.pago'
import { Route as CheckoutConfirmacionRouteImport } from './routes/checkout.confirmacion'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPagoRoute = CheckoutPagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutConfirmacionRoute = CheckoutConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/casos': typeof CasosRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/servicios': typeof ServiciosRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/pago': typeof CheckoutPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/casos': typeof CasosRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/servicios': typeof ServiciosRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/pago': typeof CheckoutPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrito': typeof CarritoRoute
  '/casos': typeof CasosRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/servicios': typeof ServiciosRoute
  '/checkout/confirmacion': typeof CheckoutConfirmacionRoute
  '/checkout/pago': typeof CheckoutPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/casos'
    | '/checkout'
    | '/contacto'
    | '/planes'
    | '/servicios'
    | '/checkout/confirmacion'
    | '/checkout/pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrito'
    | '/casos'
    | '/checkout'
    | '/contacto'
    | '/planes'
    | '/servicios'
    | '/checkout/confirmacion'
    | '/checkout/pago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/casos'
    | '/checkout'
    | '/contacto'
    | '/planes'
    | '/servicios'
    | '/checkout/confirmacion'
    | '/checkout/pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarritoRoute: typeof CarritoRoute
  CasosRoute: typeof CasosRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  PlanesRoute: typeof PlanesRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pago': {
      id: '/checkout/pago'
      path: '/pago'
      fullPath: '/checkout/pago'
      preLoaderRoute: typeof CheckoutPagoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/confirmacion': {
      id: '/checkout/confirmacion'
      path: '/confirmacion'
      fullPath: '/checkout/confirmacion'
      preLoaderRoute: typeof CheckoutConfirmacionRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutConfirmacionRoute: typeof CheckoutConfirmacionRoute
  CheckoutPagoRoute: typeof CheckoutPagoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutConfirmacionRoute: CheckoutConfirmacionRoute,
  CheckoutPagoRoute: CheckoutPagoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarritoRoute: CarritoRoute,
  CasosRoute: CasosRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactoRoute: ContactoRoute,
  PlanesRoute: PlanesRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
